services:
  - type: web
    name: jobconnect
    env: java
    plan: free                      # or starter/standard depending on your needs
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
